server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 
    url: jdbc:mysql://localhost:3306/vikas
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      
        
  mail:
    host: smtp.gmail.com
    password: pwd
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: vikasghodke54@gmail.com
reg-app: 
  messages:
    regMailSubject: User Registration Success
    regMailBodyTemplateFile: UNLOCK-ACC-EMAIL-BODY-TEMPLATE.txt